(function() {var implementors = {};
implementors["eventstore_tcp"] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='trait core::default::Default'>Default</a> for <a class='struct' href='eventstore_tcp/struct.MasterInfo.html' title='struct eventstore_tcp::MasterInfo'>MasterInfo</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='trait core::default::Default'>Default</a> for <a class='enum' href='eventstore_tcp/enum.NotHandledReason.html' title='enum eventstore_tcp::NotHandledReason'>NotHandledReason</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='trait core::default::Default'>Default</a> for <a class='struct' href='eventstore_tcp/struct.EventRecord.html' title='struct eventstore_tcp::EventRecord'>EventRecord</a>&lt;'a&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='trait core::default::Default'>Default</a> for <a class='struct' href='eventstore_tcp/struct.ResolvedIndexedEvent.html' title='struct eventstore_tcp::ResolvedIndexedEvent'>ResolvedIndexedEvent</a>&lt;'a&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='trait core::default::Default'>Default</a> for <a class='struct' href='eventstore_tcp/struct.WriteEvents.html' title='struct eventstore_tcp::WriteEvents'>WriteEvents</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='trait core::default::Default'>Default</a> for <a class='struct' href='eventstore_tcp/struct.ReadAllEvents.html' title='struct eventstore_tcp::ReadAllEvents'>ReadAllEvents</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
