(function() {var implementors = {};
implementors["eventstore_tcp"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='eventstore_tcp/enum.NotHandledReason.html' title='enum eventstore_tcp::NotHandledReason'>NotHandledReason</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='eventstore_tcp/enum.WriteEventsFailure.html' title='enum eventstore_tcp::WriteEventsFailure'>WriteEventsFailure</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='eventstore_tcp/builder/enum.ExpectedVersion.html' title='enum eventstore_tcp::builder::ExpectedVersion'>ExpectedVersion</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='struct' href='eventstore_tcp/builder/struct.StreamVersion.html' title='struct eventstore_tcp::builder::StreamVersion'>StreamVersion</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='eventstore_tcp/builder/enum.EventNumber.html' title='enum eventstore_tcp::builder::EventNumber'>EventNumber</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='eventstore_tcp/builder/enum.ContentType.html' title='enum eventstore_tcp::builder::ContentType'>ContentType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='eventstore_tcp/enum.ReadDirection.html' title='enum eventstore_tcp::ReadDirection'>ReadDirection</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
